# Generated by Django 4.0.4 on 2022-04-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieceName', models.CharField(max_length=7)),
                ('rightNumber', models.IntegerField()),
                ('leftNumber', models.IntegerField()),
            ],
        ),
    ]
